development:
  adapter: postgresql
  encoding: unicode
  database: depot_dev
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: depot_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: depot_prod
  pool: 5
  username: postgres
  password: postgres
  host: localhost
